### ISSUE TITLE
Shoppingcart db not connected to any other db

### ISSUE THREAD

**Issue by williethai** [Laracommerce/laracom#100]
Hi all,

I am new to Laravel, and we are using this git for ore e-store.
I found that the shoppingcart db table is not connected to any other table.
And it is my understanding that the "cart" just need to store data for the current session, so it doesn't need to connect to any other table.
But at least, it need to contain info about product.
is it my understanding wrong ?

Thank you very much !!

![image](https://user-images.githubusercontent.com/41844229/45670044-5acf9280-bb54-11e8-974d-d5a1682e9c74.png)

**Comment by jsdecena** [comment]
I am using: https://github.com/Crinsane/LaravelShoppingcart you can check it out how it works

**Comment by jsdecena** [comment]
If you have questions, pls use the gitter chat instead opening issues
