### ISSUE TITLE
Suggestion: Use Dependabot to automatically create dependency update PRs

### ISSUE THREAD

**Issue by greysteil** [Laracommerce/laracom#102]
First of all, thanks for Laracom!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/laracom/pulls).

I built Dependabot and give it away for free to open source projects (partly for the exposure, but mainly because it feels good to give back). I'd love you to use it - hopefully it can save you a bit of time keeping on top of dependencies, and help keep Laracom secure. It's a pretty robust product there days (over 8,000 PHP PRs merged) but if there's anything about it that you think could be better I'm always interested in feedback, too.

Thanks again for Laracom. If you do decide to give Dependabot a go on it the easiest URL to add it from is https://github.com/apps/dependabot (alternatively you can go through the GitHub Marketplace, but the flow there can be a little confusing for open-source repos on an organisation account.

:octocat:

**Comment by jsdecena** [comment]
@greysteil This is actually what I need! I keep on getting outdated dependencies on my package.json file :) Thanks for this and keep it up! We love open source :)

**Comment by greysteil** [comment]
Awesome, and thanks! ❤️

**Comment by jsdecena** [comment]
@greysteil It could have unintended effect if not carefully reviewed. I think this can be done using `composer update` and `npm update` right? I might have a reservation using your app but nevertheless, congrats on your work and God Speed!
