### ISSUE TITLE
Integration of spatie/phpunit-watcher

### ISSUE THREAD

**Issue by sebbaum** [Laracommerce/laracom#116]
For an e-commerce software, it is essential that everything is working as expected. Therefore it is important to run automated tests regularly. In the best case, the tests run on every code change. Then you get instant feedback and a notification if one of the tests fails. So you know if your tests succeed before a CI server executes them.
The laravel package phpunit-watcher by spatie is a configurable solution for this purpose.

I suggest to integrate this package and will submit a PR.

Cheers
Sebastian

**Comment by jsdecena** [comment]
Hi @sebbaum Thanks for the insight. I already associated this project with Travis. When there is a PR, it runs and gives me an email if it failed or not. :)

**Comment by sebbaum** [comment]
HI @jsdecena,

I know Travis CI. It's a great tool. However, my suggestion is also beneficial for contributors, because they don't get your notifications. By using spatie/phpunit-watcher you also shorten the feedback loop. You do not have to wait for Travis to finish the job. It also lowers the risk that broken code is committed to the repo.
Lastly, phpunit-watcher is not a replacement of Travis or any other CI server. It's more of an extra layer.

I hope, that I can confience you. :)

Cheers
Sebastian

**Comment by jsdecena** [comment]
Oh, that I didn't know. Let's see if it works for all :)

Cheers!

**Comment by jsdecena** [comment]
This can be installed on each of their forks. Thanks!
