### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by sebbaum** [Laracommerce/laracom#121]
@jsdecena Are you interested in German translations?
I can provide German translations regularly.

Cheers Sebastian

**Comment by sebbaum** [comment]
Ah now I see, that first of all the templates have to be refactored to use the language files. At the moment all text is right in the templates.

**Comment by jsdecena** [comment]
@sebbaum Yes. But there is already an issue to make it as translatable as possible https://github.com/Laracommerce/laracom/issues/92
