### ISSUE TITLE
Missing Files "front.min.js" and "style.min.css" after downloading project

### ISSUE THREAD

**Issue by mashooquecs** [Laracommerce/laracom#123]
I've just installed laracommerce/laracom at my system multiple times, but there are two files missing in that projects.

1.front.min.js
2. style.min.css

Can you suggest or Help me out this? I'll be very thankful to you for your help

**Comment by phannaly** [comment]
@mashooquecs Did you follow the installation guide here [Installation](https://shop.laracom.net/docs/1.4.6/installation)

**Comment by mashooquecs** [comment]
phannaly.
I didn't follow with LARAVEL Homestead, I've used Artisan to download project. 
And I guess they said this "There are many ways to install a Laravel app but we suggest using Homestead."

**Comment by jsdecena** [comment]
@mashooquecs You should build the assets. Kindly run `npm install && npm run dev` to compile these missing files :)
