### ISSUE TITLE
Inability to authenticate consistently in admin

### ISSUE THREAD

**Issue by juddfranklin1** [Laracommerce/laracom#126]
Hello there. Thank you for the excellent project!

I was wondering if you could provide me some guidance on the way that auth works on the admin.

I have been trying to give the `admin.products.show` route the same edit and delete buttons that are available for each product in the standard products admin list route (`admin.products.index`).

I was able to do this by including the `admin.shared.products` partial, but the `$admin->hasPermission` check is not available in the views that aren't in the 'shared' folder.

Why is the $admin variable available only to the `admin.shared` partials, and not to the `admin.products.show` view? How can I change this?

Thank you again!

**Comment by belguinan** [comment]
admin variable is shared over the view composer
You can check it in your GlobalTemplateServiceProvider

```
view()->composer([
            'layouts.admin.app',
            'layouts.admin.sidebar',
            'admin.shared.products'
        ], function ($view) {
            $view->with('admin', Auth::guard('employee')->user());
        });
```

Full path :[https://github.com/Laracommerce/laracom/blob/master/app/Providers/GlobalTemplateServiceProvider.php](Here)

**Comment by juddfranklin1** [comment]
Thanks @belguinan

**Comment by jsdecena** [comment]
> Why is the $admin variable available only to the admin.shared partials, and not to the admin.products.show view? How can I change this?

As @belguinan said, that variable exists in the `GlobalTemplateServiceProvider`. 

@juddfranklin1 If you wish to have that variable available, you can set it in your `show()` method as: 

```php
...
$admin = $request->user('employee');
return response()->json(compact('admin'));

...
// In html template
{{dd($admin)}}
```
