### ISSUE TITLE
Migrate to Laravel 5.7

### ISSUE THREAD

**Issue by belguinan** [Laracommerce/laracom#133]
It would be good if we migrate to Latest version of Laravel. 
It's not required but we will have many features added, The only package that don't support 5.7 is shopping cart.

**Comment by jsdecena** [comment]
@belguinan and that is the core of this app right? :) There is already an issue created for the [package](https://github.com/Crinsane/LaravelShoppingcart/issues/498) so we just wait it out

**Comment by belguinan** [comment]
> package

I am afraid if something went wrong with the developer or just on vacation for some "months"

**Comment by jsdecena** [comment]
@belguinan Upgraded to L5.7 See commit https://github.com/Laracommerce/laracom/commit/7ec40a5df2a4e748d483611bfbde96998e08fc3f

**Comment by belguinan** [comment]
> @belguinan Upgraded to L5.7 See commit [7ec40a5](https://github.com/Laracommerce/laracom/commit/7ec40a5df2a4e748d483611bfbde96998e08fc3f)

@jsdecena I think we need to refactor the code, routes... We can use dependency injection instead of getting new item by id on database. What do you think? Why we need repositories instead of the default tools provided?

**Comment by belguinan** [comment]
@jsdecena Routes CRUD. instead of calling find product by id for exemple we can just typehint Product on controller

**Comment by jsdecena** [comment]
That is done because development starts with tests (TDD). We need to create reusable methods and test it if it works. So every time we use it we know that the method we create is always working.

**Comment by belguinan** [comment]
@jsdecena I understand
