### ISSUE TITLE
Adding additional pages to Admin

### ISSUE THREAD

**Issue by chrisformula** [Laracommerce/laracom#134]
How can I add additional pages to admin? everytime I try and add I get Route not defined.

**Comment by jsdecena** [comment]
Show us your code

**Comment by chrisformula** [comment]
`
            Route::namespace('Posts')->group(function () {
                Route::resource('post-categories', 'PostCategoriesController@index');
            });`

**Comment by belguinan** [comment]
@chrisformula  Check your route name in artisan, just type `php artisan route:list`. Or name your routes. 
Visit routing documentation for more details [here](https://laravel.com/docs/5.7/routing)
