### ISSUE TITLE
LogicException: Node must not be a descendant.

### ISSUE THREAD

**Issue by mnestorov** [Laracommerce/laracom#136]
@jsdecena , first of all, BIG thank you for your nice work!

I have some issues with categories. When I try to update parent category I get "LogicException: Node must not be a descendant." error. How can I fix this?

Thanks,
Martin

**Comment by belguinan** [comment]
Maybe the parent id is set on the request? can you provide more details about the issue?

**Comment by mnestorov** [comment]
Well, my `rules()` function in **UpdateCategoryRequest** class, return this:

` return ['name' => ['required', Rule::unique('categories')->ignore(request()->segment(3))]];`

And this is the error message;
![capture](https://user-images.githubusercontent.com/8516554/48264351-db628f00-e431-11e8-812f-02fec0dfe031.JPG)

Maybe if you tell me exactly where to look for the problem, I'd be more useful.

**Comment by belguinan** [comment]
@mnestorov Try to test if the category currently updated is the same as selected parent.

In **CategoryRepository@updateCategory**
You'll find this test

`
if (isset($params['parent'])) ...
`

Make it like this:

`isset($params['parent']) && $params['parent'] != $this->model->id`

Then test if it works. I didn't test this if really it causes the issue but give it a try.
I will check it for you later and i'll let you know.

**Comment by mnestorov** [comment]
> @mnestorov Try to test if the category currently updated is the same as selected parent.
> 
> In **CategoryRepository@updateCategory**
> You'll find this test
> 
> `if (isset($params['parent'])) ...`
> 
> Make it like this:
> 
> `isset($params['parent']) && $params['parent'] != $this->model->id`
> 
> Then test if it works. I didn't test this if really it causes the issue but give it a try.
> I will check it for you later and i'll let you know.

Unfortunately, it does not work. Same error message.

This happened only when I try to update parent category. If I try to update top category with no child categories, there is no problem.

**Comment by belguinan** [comment]
Just tested manually I couldn't reproduce the issue. If you can describe how to reproduce it. Will be great for solving your issue.

**Comment by mnestorov** [comment]
I found the problem ... It's very stupid, but ... Everything comes from the drop-down menu "Parent category". Because we can only choose which category to be a parent, and when we update the parent category, then the clash comes. I've also made a video.

[https://youtu.be/-gWcI6iEP_Q](url)

**Comment by belguinan** [comment]
> I found the problem ... It's very stupid, but ... Everything comes from the drop-down menu "Parent category". Because we can only choose which category to be a parent, and when we update the parent category, then the clash comes. I've also made a video.
> 
> https://youtu.be/-gWcI6iEP_Q

Right! chosen parent category should be optional.

**Comment by belguinan** [comment]
@mnestorov Here is the [the fix](https://github.com/Laracommerce/laracom/pull/135/commits/e289448df3b3355a70972d8510655b9248d47107)

**Comment by mnestorov** [comment]
@belguinan thank you very much for your help. This issue has been solved.
