### ISSUE TITLE
Order product statuses

### ISSUE THREAD

**Issue by michael-hampton** [Laracommerce/laracom#154]
I think it would be better if order product lines had independent statuses this way you could do things like refund a line. Unfortunately at the moment there is no order product models or repository because everything is done directly from orders which makes it difficult to change or add functionality

**Comment by jsdecena** [comment]
Hi, @michael-hampton if you have an idea, I am open to it.

**Comment by michael-hampton** [comment]
Basically order product should be its own repository/model with update functionality and find by id. This way you could have a status column in the order_product table which would be editable . I think you had it like this previously but it was removed and now only manageable through the order models
