### ISSUE TITLE
Amount paid for order discrepancy 

### ISSUE THREAD

**Issue by michael-hampton** [Laracommerce/laracom#155]
If the order is done by bank transfer then there is a warning displayed because of a discrepancy in the price / total paid. This is because for a bank transfer the amount paid is 0. This isn’t a discrepancy it’s just that the amount hasn’t been received.

**Comment by jsdecena** [comment]
Yes that is correct.

**Comment by michael-hampton** [comment]
Why is it correct. Surely if its a bank transfer then it would be better to have the message time limited for example for bank transfers so if no money received within 30 days then show the message. It is understandable that a bank transfer wont be received the exact same time the order is made. And secondly how do we update the order table total paid column to say that the bank transfer has been received?
