### ISSUE TITLE
PayPal checkout transactions.amount.currency

### ISSUE THREAD

**Issue by farry19** [Laracommerce/laracom#160]
When checkout with paypal, it gives error `transactions.amount.currency` on local valet.

**Comment by JoseanMF** [comment]
Me ocurre lo mismo

**Comment by jsdecena** [comment]
@farry19 It must be something in the `.env` As you can see here: https://shop.laracom.net, everything is working correctly as expected.

**Comment by JoseanMF** [comment]
Do the paypal tests at https://shop.laracom.net, produce real payments?

Thank you.

**Comment by jsdecena** [comment]
@JoseanMF not yet but it is the sandbox of Paypal. When everything goes smoothly in the sandbox, it should not have a problem in live production.

**Comment by JoseanMF** [comment]
> @farry19 It must be something in the `.env` As you can see here: https://shop.laracom.net, everything is working correctly as expected.

SHIPPING_COST=0
TAX_RATE=0
DEFAULT_CURRENCY=usd
CURRENCY_SYMBOL=$

En el fichero .env el parámetro DEFALULT_CURRENCY=usd tiene que ser cambiado por DEFAULT_CURRENCY=USD. O sea, debe ponerse en mayúsculas para que funcione bien.

In the .env file the parameter DEFALULT_CURRENCY = usd has to be changed by DEFAULT_CURRENCY = USD. That is, it must be capitalized to work well.

**Comment by jsdecena** [comment]
Closing since it should be resolved by now.
