### ISSUE TITLE
Undefined Variable 'combos'

### ISSUE THREAD

**Issue by igrlima** [Laracommerce/laracom#162]
app\Http\Controllers\Front\ProductController.php 

The view is returned with five variables while the select for the last 'combos' are missing

 public function show(string $slug)
    {
        $product = $this->productRepo->findProductBySlug(['slug' => $slug]);
        $images = $product->images()->get();
        $category = $product->categories()->first();
        $productAttributes = $product->attributes; 

        return view('front.products.product', compact(
            'product',
            'images',
            'productAttributes',
            'category',
            **'combos'**
        ));
    }

**Comment by jsdmultisys** [comment]
@igrlima where is your combos in the controller?

**Comment by jsdecena** [comment]
closing as there is no reply

**Comment by singhpk89** [comment]
@jsdmultisys , @jsdecena I am also getting the same issue 
compact(): Undefined variable: combos in  ProductController at line no 66.

 public function show(string $slug)
    {
        $product = $this->productRepo->findProductBySlug(['slug' => $slug]);
        $images = $product->images()->get();
        $category = $product->categories()->first();
        $productAttributes = $product->attributes;

        return view('front.products.product', compact(
            'product',
            'images',
            'productAttributes',
            'category',
            'combos'
        ));
    }

**Comment by AMAFsoft** [comment]
Same here, in front show product
