### ISSUE TITLE
Custom Exception

### ISSUE THREAD

**Issue by rkbwp** [Laracommerce/laracom#163]
First of all thanks for your wonderful product.

I've a question regarding to the error handling. I saw that you are using custom exception in repositories of each model. I am wonder that how and where those custom exceptions are being used? I am asking for this for knowledge purpose. And how do I show user friendly error messages on frontend. 

Looking forward to hear from you a supportive reply.

thanks

**Comment by jsdmultisys** [comment]
@rkbwp It is used so when a developer catches an error, he knows already what is going on by reading the custom error class eg. `UserNotFoundErrorException` vs `ModelNotFoundException`

you can show user friendly error in frontend by catching these custom error handlers in the controller like:

```
// UserController.php

try {
     ...
     $user = $this->userRepo->findUserById($id);
     return response()->json($user);

} catch(UserNotFoundErrorException $e) {

 return response()->json(['error' => 'The user is not found.'], 404)

}
```

**Comment by rkbwp** [comment]
@jsdmultisys Thanks for your prompt response.

I got your point that how I can catch the exception and show a user friendly error messages. But in app/Http/Controllers/Admin/Customers/CustomerController.php in the store method you are not catching the exception which you've thrown in the Customer repository. 

`public function store(CreateCustomerRequest $request)
{
     $this->customerRepo->createCustomer($request->except('_token', '_method'));
     return redirect()->route('admin.customers.index');
}`

Are you handling the exception in another file or handling in some another way. If not what would happen if on something break while storing the data?

Looking forward to hear from you. 

Thanks in advance.

**Comment by jsdmultisys** [comment]
I might not have been consistent. A PR should be nice! :)

**Comment by jsdecena** [comment]
Closing since an explanation is already provided.
