### ISSUE TITLE
https://shop.laracom.net/docs) exposes info

### ISSUE THREAD

**Issue by ekordev** [Laracommerce/laracom#165]
https://shop.laracom.net/docs works but `https://shop.laracom.net/docs)` exposes information

**Comment by jsdecena** [comment]
@ekordev what do you mean?

**Comment by ekordev** [comment]
If you go to https://shop.laracom.net/docs you see this 
![Screenshot_2019-03-25-20-39-22](https://user-images.githubusercontent.com/22979362/54970216-8b96e700-4f3e-11e9-8f39-b04b812560a4.png)

But if you add a parenthesis at the end like so https://shop.laracom.net/docs) you see this
![Screenshot_2019-03-25-20-40-14](https://user-images.githubusercontent.com/22979362/54970292-d0bb1900-4f3e-11e9-8f73-ff4f768ee97b.png)

Which shows settings that shouldn't be shown in production

**Comment by enricoromeo** [comment]
It's a common (not managed) error 404.

Il Mar 26 Mar 2019, 04:46 Ekor <notifications@github.com> ha scritto:
