### ISSUE TITLE
null address_id when using bank transfer mode of payment

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [Laracommerce/laracom#173]
by default address id is been added at time of address creation 
when checking out of cart from bank transfer mode address_id null error occurs 
and stop futher procedure from executing...

C:\xampp\htdocs\laracom\app\Shop\Orders\Repositories\OrderRepository.php
     * Create the order
     *
     * @param array $params
     * @return Order
     * @throws OrderInvalidArgumentException
     */
    public function createOrder(array $params) : Order
    {
        try {
 
            $order = $this->create($params);
 
            $orderRepo = new OrderRepository($order);
            $orderRepo->buildOrderDetails(Cart::content());
 
            event(new OrderCreateEvent($order));
 
            return $order;
        } catch (QueryException $e) {
            throw new OrderInvalidArgumentException($e->getMessage(), 500, $e);
        }
    }
"**SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'address_id' cannot be null (SQL: insert into `orders` (`reference`, `courier_id`, `customer_id`, `address_id`, `order_status_id`, `payment`, `discounts`, `total_products`, `total`, `total_paid`, `total_shipping`, `tax`, `updated_at`, `created_at`) values (50ee7968-3c89-4496-9b26-3b04ac3bd204, 1, 14, , 2, enquiry orders, 0, 50.00, 21.00, 0, 0, 0.00, 2019-04-20 10:20:32, 2019-04-20 10:20:32)) ◀"**

![image](https://user-images.githubusercontent.com/11476137/56490974-a0967400-6504-11e9-8312-1c499085fd3c.png)

**Comment by Kalpeshpatelbyk** [comment]
not able to figure out how values in address_id suddenly stoped working 
tracing error since 3 days but no result yet.... please consider this request asap

**Comment by jsdmultisys** [comment]
you need to pass the `address_id` in the request. It must be an existing address ID in your database

**Comment by Kalpeshpatelbyk** [comment]
> you need to pass the `address_id` in the request. It must be an existing address ID in your database

can you please elobrate as such previously things were working fine suddenly this error start popping up
i had checked controller and used dd funtion on checkout.blade.php addressid is showing properly but some how not able to update .. help will pe appreciated

**Comment by chrisformula** [comment]
@Kalpeshpatelbyk did you manage to figure it out?

**Comment by jsdecena** [comment]
In the form, you just need to pass an `address_id` as the billing address.

**Comment by chrisformula** [comment]
`<div class="btn-group">
                                <a href="{{ route('checkout.index') }}" class="btn btn-default">Back</a>
                                <button onclick="return confirm('Are you sure?')" class="btn btn-primary">Pay now with Bank Transfer</button>
                                <input type="hidden" id="billing_address" name="billing_address" value="{{ $billingAddress }}">
                                <input type="hidden" name="shipment_obj_id" value="{{ $shipmentObjId }}">
                                <input type="hidden" name="rate" value="{{ $rateObjectId }}">
                                @if(request()->has('courier'))
                                    <input type="hidden" name="courier" value="{{ request()->input('courier') }}">
                                @endif
                            </div>`

As soon as I change $billingAdress to anything else I get the error

**Comment by jsdecena** [comment]
You need to check `$billingAddress` variable in the controller. set value of `1` for now, but this should be dynamic. You must save the address chosen by the customer as their billing address id and set it there.

**Comment by chrisformula** [comment]
I haven’t changed anything from the original code that is what is so weird about it. I do need it be dynamic as I want to test multiple users and multiple addresses for a single user

**Comment by chrisformula** [comment]
@Jsdecena

**Comment by jsdecena** [comment]
if it is, then it should be a bug. I would appreciate any help at this moment.

**Comment by chrisformula** [comment]
@jsdecena I'll sort it out and send you a PR bro

**Comment by chrisformula** [comment]
@jsdecena @Kalpeshpatelbyk The issue happens when you use custom css and js. Make sure that Jquery is called in the header and not the footer that will solve the issue.

**Comment by Kalpeshpatelbyk** [comment]
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    
    <script src="{{asset('js/bootsnav.js')}}"></script>
@yield('js') 
    this code is from my app.blade.php 
i had not added any script or jquery in footer  but issues still persist

**Comment by chrisformula** [comment]
@Kalpeshpatelbyk where did you place the @yield('js') in the app.blade?

**Comment by Kalpeshpatelbyk** [comment]
> jsdecena @Kalpeshpatelbyk The issue happens when you use custom css and js. Make sure that Jquery is called in the header and not the footer that will solve the issue

YES SIR THANK U FOR RESOLVING YOUR QUERY.... I USED HEAD TAG FOR JS AND THINKG WORK PERFECTLY FINE ....

**Comment by Kalpeshpatelbyk** [comment]
> @Kalpeshpatelbyk where did you place the @yield('js') in the app.blade?
> 
> You have to make sure that your jquery is called in the header. That is what solved it for me

YES SIR THANKS ... WORK AS U SAID

**Comment by chrisformula** [comment]
@Kalpeshpatelbyk Glad I could help my friend

**Comment by chrisformula** [comment]
@jsdecena You can close this item
