### ISSUE TITLE
Get list of cart item on app.blade.php

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [Laracommerce/laracom#174]
Please anyone had idea i want to get list of selected cart item in menu section under cart menu on home page . been trying from long help will be appreciated

**Comment by Kalpeshpatelbyk** [comment]
@foreach(Cart::content() as $row) 
                            <tr>
                            <th><i class="fa fa-cog" aria-hidden="true" style="color:blue;">&nbsp;&nbsp;</i><strong>{{$row->name}}</strong></th>
                            <th><i class="fa fa-arrow-circle-right" aria-hidden="true"  style="color:red;"></i></th>
                            <th class="pull-right"><strong>{{$row->qty}}</strong></th>
                            </tr>
                            <tr>
                            @endforeach

**Comment by jsdecena** [comment]
There is a global template with global variable for specific template that you can use. Check it here: https://github.com/Laracommerce/laracom/blob/master/app/Providers/GlobalTemplateServiceProvider.php
