### ISSUE TITLE
Exception at address delete

### ISSUE THREAD

**Issue by marpal71** [Laracommerce/laracom#179]
If all address are deleted after an order has been placed, an application error raises with exception AddressNotFoundException.

**Comment by marpal71** [comment]
Found the problem ! Trying to fix it. An explanation will follow.

**Comment by Kalpeshpatelbyk** [comment]
if you drop table and create again apprantely deleting all previous order details is shows no error perhaps 
foreign key is seeking for id which is softdeleted from database with status active..

**Comment by jsdecena** [comment]
I think, a user should not be able to delete an address since a transaction is tied to an address.

**Comment by marpal71** [comment]
The problem is that softdelete is used for address table. if an order has been placed ans customer deletes its address, the relative order's address is not picked up in the query because address's deleted_at field has a time_stamp.

    Fix goes either implementing a new function which use the queryBuilder ->withTrashed() for order related stuff.

 I beleive long wotk as there will be need to cover new functionality with new tests to pass codecov cover.

**Comment by marpal71** [comment]
> I think, a user should not be able to delete an address since a transaction is tied to an address.

@jsdecena he can actually

**Comment by jsdecena** [comment]
So, it should not be permitted. He can only disable the address but not delete if that address already has a transaction associated with it.

**Comment by marpal71** [comment]
Pr #182 just as you said.

    cheers.
