### ISSUE TITLE
customer is erroneosly redirected to admin login

### ISSUE THREAD

**Issue by marpal71** [Laracommerce/laracom#180]
If a customer has more then one address, and you delete one of it in the "My account" section, the subsequent loaded view (resources/views/front/customers/addresses/list.blade.php) routes the available actions "edit" and "delete" to admin prefixed routes. So if the user try to "edit" or "delete" the remaining address, he is redirected to the admin login page.
Cheers

**Comment by Kalpeshpatelbyk** [comment]
same issue here too..

**Comment by jsdecena** [comment]
the redirect link might be wrong. pls check.

**Comment by marpal71** [comment]
> the redirect link might be wrong. pls check.
@jsdecena yes, it's wrong. It goes to something like admin.*

  Should be easly fixed. I can do a Pr.

**Comment by jsdecena** [comment]
Looking forward to a PR
