### ISSUE TITLE
Product list not shown in category/slug page

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [Laracommerce/laracom#181]
Created Product with cover images as temporay then updated the cover image of product items 
with status =1 ( active ) some how product with changed cover does not display in page but when used dd($product) in category its show list of product according to category.

![image](https://user-images.githubusercontent.com/11476137/57199721-cf4e2900-6f9f-11e9-9afb-daaa28036ff5.png)

**Comment by jsdecena** [comment]
@Kalpeshpatelbyk Can you check if the the update causes the status be updated also to `0`?

**Comment by Kalpeshpatelbyk** [comment]
when we change cover image with status as active then problem arise. being all parameter same cover images with first time upload displays properly but once they are updated only one first image of array displays
