### ISSUE TITLE
Admin password recovery redirected to home page

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [Laracommerce/laracom#186]
how to reset password for admin panel and register new admin user. 
new user created is saved as customer in customer table then in employee table 
no provision for employee is created ...

**Comment by jsdecena** [comment]
If this is still in development, do `php artisan migrate:refresh --seed`

**Comment by Kalpeshpatelbyk** [comment]
yes migration is working properly but when u set to recovery password it had no option can we use mail reset link to user

**Comment by jsdecena** [comment]
You can PR if you find a solution on this.
