### ISSUE TITLE
Product Search Images issue

### ISSUE THREAD

**Issue by Kalpeshpatelbyk** [Laracommerce/laracom#194]
Sir, On Product Search there are some issues regarding display of product images
path for images had double path in same string.
   img src="**http://127.0.0.1:8000/storage/http://127.0.0.1:8000/storage/products/sGTQqSh8QZPZyodCHbj0qEDwTsV5n4dyyxGZkIde.jpeg**" alt="zz" class="img-bordered img-responsive"

**Comment by jsdecena** [comment]
I think the transformer is doing it. You can PR a fix. Thanks!
