### ISSUE TITLE
Failed to clear cache. Make sure you have the appropriate permissions.

### ISSUE THREAD

**Issue by fantashi** [Laracommerce/laracom#200]
I try a new setup with document on vagrant, then I'm on `vagrant ssh` then run code `php artisan cache:clear`, this issue appear `Failed to clear cache. Make sure you have the appropriate permissions.`.

Could you have solution on this issue.
Thank you!

**Comment by Daniyal-Javani** [comment]
Can you `cd` to app directory and run these commands?
```
sudo chown -R $USER:www-data .
sudo find . -type f -exec chmod 664 {} \;
sudo find . -type d -exec chmod 775 {} \;
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
```

**Comment by fantashi** [comment]
@Daniyal-Javani thanks for your comment, but I using laravel homestead on vagrant. I don't have user group www-data, just have vagrant user. In storage folder just have app, framework, logs. Why we need chmod and chown for this?
