### ISSUE TITLE
Cart Currency and Cart Symbol Can not be change.

### ISSUE THREAD

**Issue by vijayrami** [Laracommerce/laracom#202]
I tried to change cart items defult currency abd currency symbol from config/cart.php.

but nothing worked.

i also run all necessary laravel commands:

php artisan config:cache
php artisan config:clear
php artisan cache:clear
php artisan route:clear
php artisan view:clear
php artisan clear-compiled
composer dump-autoload

But no change reflecting.

**Comment by jsdecena** [comment]
If you didn't read the documentation you will not know how. Change the values in the `.env`
