### ISSUE TITLE
No https-only flag in xsrf cookie

### ISSUE THREAD

**Issue by kukuxumushi** [Laracommerce/laracom#212]
Hello.

Without http-only flag, it is possible to steal xsrf token (through reflected xss, for example :^) ) and this protection becomes useless.

I think its a good idea to set this flag.

Thx.

**Comment by belguinan** [comment]
@kukuxumushi If XSS was fixed, then no need for the flag right?

**Comment by kukuxumushi** [comment]
Most likely not required.
