### ISSUE TITLE
No proper validation when adding alpha numeric value in quantity.

### ISSUE THREAD

**Issue by channaveer** [Laracommerce/laracom#214]
Hi, When we add non-numeric ie any alphabet in the following process than the application breaks instead of property validation.

How to reproduce
-----------------

1. Hover on any product

2. Quick View 

3. In place of quantity if I add alphanumeric it breaks the page.

**Comment by jsdecena** [comment]
Hi @channaveer You can always help the community by making PR :)

**Comment by channaveer** [comment]
@jsdecena Sure I will work on the same and create the test cases and send the PR
