### ISSUE TITLE
Feature Request: Support multiple stock and prices

### ISSUE THREAD

**Issue by viezel** [Laracommerce/laracom#26]
Often in Ecommerce the products have different prices and stock level in each country. Being able to define those in Laracom would be a great feature.

**Comment by jsdecena** [comment]
@viezel this is a bit advanced and if you have time to collaborate on that feature, you are very much welcome! 

For now, there is the product combination which you may assign **quantity** per **combination** and it sums up to make your total stock inventories. :)

**Comment by viezel** [comment]
Sure - Ill gladly help out. Yeah it is advanced but would make laracom much more flexible for different client needs.

**Comment by jsdecena** [comment]
I agree. That would be a game changer actually 😃

**Comment by viezel** [comment]
same here.. lets reopen.

**Comment by viezel** [comment]
moved https://github.com/Laracommerce/core/issues/3
