### ISSUE TITLE
Feature Request: Make into package

### ISSUE THREAD

**Issue by viezel** [Laracommerce/laracom#27]
Instead of shipping Laracom as a whole laravel app, it would make more sense to have it as a composer package. Then people have full freedom to build their ecommerce site as they want. Its also much easier for you/us to maintain. 

Ill gladly help out on this.

**Comment by jsdecena** [comment]
I have properly namespaced everything so porting it into a package should be possible. :) I just do not have the luxury of the time to do it. 😃

**Comment by viezel** [comment]
why closing this if you like the idea? 
instead it could go into a milestone for planning.

**Comment by viezel** [comment]
can you create a laracom github organisation? then we could make a package out of it.

**Comment by jsdecena** [comment]
@viezel I have created and added you in the organization :)

**Comment by viezel** [comment]
@jsdecena can you please create a repo named "Core" inside the organisation?

**Comment by jsdecena** [comment]
@viezel Sure. Hold on.

**Comment by jsdecena** [comment]
done. @viezel https://github.com/Laracommerce/core

**Comment by jsdecena** [comment]
They decided to make their work as a private repository. Thanks for being a part of Laracom for a short time. :) Good luck!

**Comment by lankasenanayaka** [comment]
I also like to help on this

**Comment by jsdecena** [comment]
@lankasenanayaka cool
