### ISSUE TITLE
Issue: Inconsistent currency labels

### ISSUE THREAD

**Issue by dmitrij-schmidt** [Laracommerce/laracom#28]
**Description:**
Currency labels are inconsistent throughout the project. 
In many places they are hardcoded to PHP, for an example in admin/products/show.blade.php they are coded as `<td>Php {{ $product->price }}</td>`.

On this stage (unless there is a plan to support multiple currencies), currency name should be echoed as in admin/shared/products.blade.php  `<td>{{ config('cart.currency') }} {{ $product->price }}</td>`

Quick search showed 8 results in 6 files:
admin/orders/list.blade.php 
admin/orders/show.blade.php
admin/products/create.blade.php
admin/products/show.blade.php
admin/products/edit.blade.php
front/accounts.blade.php

This is quite easy to fix using find/replace in any modern editor (took me like 10 seconds on my local copy). I'm only a beginner when it comes to PHP tests and using github in general, so I'll just post it for now.

**Comment by jsdecena** [comment]
Hi @dmitrij-schmidt Nice catch! Thank you. I have made the correction in the develop branch, see this commit https://github.com/Laracommerce/laracom/commit/bee94cff69c192fde091cc240f7e7cacc31560b6
