### ISSUE TITLE
Issue: wrong categories assigned to "Newest" and "Featured"

### ISSUE THREAD

**Issue by dmitrij-schmidt** [Laracommerce/laracom#29]
**Description**
"Newest" and "Featured" categories are assigned to wrong ID's during initial seeding of the database. 

This is the code from HomeController, that gets the categories based on statically assigned ID's and pushes them to front views:
```
public function index()
    {
        $category2 = $this->categoryRepo->findCategoryById(2);
        $category3 = $this->categoryRepo->findCategoryById(3);

        $newests = $category2->products;
        $features = $category3->products;


        return view('front.index', compact('newests', 'features', 'category2', 'category3'));
    }
```

but as the database is seeded by Faker including calling randomElement() method on an array of categories (database/factories/CategoryModelFactory.php)
```
$name = $faker->unique()->randomElement([
        'Newest',
        'Featured',
        'Gear',
        'Clothing',
        'Shoes',
        'Diapering',
        'Feeding',
        'Bath',
        'Toys',
        'Nursery',
        'Household',
        'Grocery'
    ]);
``` 
ID's of seeded categories will be different for each installation, e.g. in my case:
ID 2 is not "Newest", but "Diapering"
ID 3 is not "Featured", but "Household"

Probably these two root categories (Newest and Featured) can be moved to a static categories seeder, which currently seeds only "Uncategorized" at ID of 1? That would explain usage of static ID's of 2 and 3 in HomeController

**Comment by jsdecena** [comment]
@dmitrij-schmidt Thank you. Fixed this on https://github.com/Laracommerce/laracom/commit/c5a226540d22a352573e9518e49be7c4c55ce9ba
