### ISSUE TITLE
ERROR: Installation

### ISSUE THREAD

**Issue by rizdem** [Laracommerce/laracom#32]
I started a fresh install but I am receiving 404 errors for files.
I have created the symlink (php artisan storage:link) for public/storage still no luck. Have I missed a step. Also the Installation link points to another fork for your project. 

<img width="1275" alt="screen shot 2018-03-19 at 12 58 54" src="https://user-images.githubusercontent.com/15727905/37596871-7b911be8-2b75-11e8-9dc6-5d6c99b0fd87.png">
<img width="1275" alt="screen shot 2018-03-19 at 12 58 39" src="https://user-images.githubusercontent.com/15727905/37596875-7dc4e264-2b75-11e8-8e8d-9449765baa84.png">

**Comment by jsdecena** [comment]
You need to run `npm run dev` to compile the assets 😉

**Comment by rizdem** [comment]
Hey Sorry never run an npm command. Do you think my machine is missing something.

<img width="668" alt="screen shot 2018-03-19 at 15 22 03" src="https://user-images.githubusercontent.com/15727905/37604682-701e4998-2b89-11e8-82dc-abd09a653a80.png">
<img width="671" alt="screen shot 2018-03-19 at 15 22 55" src="https://user-images.githubusercontent.com/15727905/37604685-70938df2-2b89-11e8-81ee-c0ad79f099db.png">

**Comment by jsdecena** [comment]
Yup. Here's the [instruction](https://github.com/Laracommerce/laracom/wiki/Installation#build-and-compile-assets)

**Comment by rizdem** [comment]
Cheers 👍🏻
