### ISSUE TITLE
Issue: Images Not Displaying

### ISSUE THREAD

**Issue by rizdem** [Laracommerce/laracom#33]
Hi the images for products aren't displaying. I have ensured I have run "php artisan storage:link" the images have loaded correctly in to "storage/app/public/products/xxxxxxxx.jpg"

Console is reporting a 404 "Not Found"

Any ideas 

<img width="495" alt="screen shot 2018-03-20 at 19 50 24" src="https://user-images.githubusercontent.com/15727905/37679308-6ff72260-2c78-11e8-8947-0aedb557f162.png">

**Comment by jsdecena** [comment]
depending on your set up for local development, but in Homestead. You need to go into the vagrant instance then you have to issue the storage link command. I think there is an issue for doing symlink with laravel when you do it outside the vagrant instance.

1. `cd ~/Homestead`
2. `vagrant ssh`
3. `cd /to/your/project`
4. `php artisan storage:link`

**Comment by rizdem** [comment]
That worked thank you. I must of created the symlink outside. Cheers
