### ISSUE TITLE
Issue: Unable to delete product with associated images

### ISSUE THREAD

**Issue by codegenin** [Laracommerce/laracom#34]
Description:

When trying to delete a product having 1 or more images associated in product_images table. 

`SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`laracom`.`product_images`, CONSTRAINT `product_images_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)) (SQL: delete from `products` where `id` = 49)`

maybe add a cascade on delete in the migration file or a process to delete the associated entries in product_images first then remove its images in the products directory.

**Comment by jsdecena** [comment]
Hi @codegenin Here's the fix on the issue: https://github.com/Laracommerce/laracom/commit/4d5d37ac201a059249b29ce8d14822ff400a8695 However, it is just in the `develop` branch

**Comment by codegenin** [comment]
Thanks @jsdecena
