### ISSUE TITLE
Feature Request: Upgrading to bootstrap 4.

### ISSUE THREAD

**Issue by klukiyan** [Laracommerce/laracom#35]
Hi,
first of all big thank you. Very good project and very nice that it uses latest laravel.
Can you please give me a hint what would be the right way to upgrade to bootstrap 4.0 in front-end?

**Comment by olivercastro** [comment]
I'm not sure if this is correct it working on my end.

I've added the following entries under the "dependencies" of package.json

`"bootstrap": "^4.0.0",`
`"popper.js": "^1.14.1",`

Run npm install

Update webpack.mix.js

`.scripts(
        [
            'node_modules/popper.js/dist/umd/popper.js',
            'resources/assets/js/jquery-2.2.3.min.js',
            'node_modules/bootstrap/dist/js/bootstrap.js',
            'node_modules/select2/dist/js/select2.js',
            'node_modules/datatables/media/js/jquery.dataTables.js',
            'resources/assets/admin-lte/js/app.js'
        ],
        'public/js/admin.min.js'
    )`

I hope this helps

**Comment by klukiyan** [comment]
@olivercastro  thank you. I'll try it
