### ISSUE TITLE
Admin panel treeview

### ISSUE THREAD

**Issue by belguinan** [Laracommerce/laracom#37]
Hello,
After installing laracom i found that the admin left bar can't open the submenu
even if i try to click on ".treeview"

Should i hardcode it again ? or it's a bug?

**Comment by jsdecena** [comment]
it's working. please ensure you clone the package, run `npm install` and `npm run dev` to properly compile the assets. You should also have the latest npm and node. I suggest use NVM https://github.com/creationix/nvm

**Comment by belguinan** [comment]
Hello, No it doesnt work, i did all the steps on the documentation and nothing,
I added this code into my js file.

$('body').on('click', '.treeview a', function(e){
    var link = $(this);

    if( link.attr('href') == '#' )
    {
        var nextMenu = link.next('.treeview-menu')

        if( nextMenu.length )
        {
            nextMenu.slideToggle()
        }
    }
})
