### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by belguinan** [Laracommerce/laracom#38]
Hello,
I can't search on any controller/model
it looks laracom is using this module to make search query's

https://github.com/jarektkaczyk/eloquence/wiki/Base

"SQLSTATE[42000]: Syntax error or access violation: 1055 'laracom.products.sku' isn't in GROUP BY (SQL: select * from (select `products`.*, max(case when `products`.`name` = asd then 15 else 0 end + case when `products`.`name` like asd% then 5 else 0 end + case when `products`.`name` like %asd% then 1 else 0 end) as relevance from `products` where (`products`.`name` like %asd%) group by `products`.`id`) as `products` where `relevance` >= 0.25 order by `relevance` desc)

**Comment by jsdecena** [comment]
Search is also working. We have the test in [here](https://github.com/Laracommerce/laracom/blob/master/tests/Feature/Admin/Products/ProductFeatureTest.php#L26) and it is passing.

**Comment by belguinan** [comment]
Hello,
Thank you,
Here is the solution
https://stackoverflow.com/questions/40917189/laravel-syntax-error-or-access-violation-1055-error
