### ISSUE TITLE
limit product in category page

### ISSUE THREAD

**Issue by dimasip** [Laracommerce/laracom#45]
i try to limit product per page in category page.

i can customize limit in **search page**.
        return view('front.products.product-search', [
            'products' => $this->productRepo->paginateArrayResults($products->all(), 10)
        ]);

how to limit product in category page?

**Comment by jsdecena** [comment]
@dimasip The same. Get the all the products in an array then paginate.

**Comment by authemany2k** [comment]
Pls implement i have been struggling with it for a while now

**Comment by jsdecena** [comment]
@authemany2k How about:

```
$category = $this->categoryRepo->findCategoryById($id);
$paginated = $this->categoryRepo->paginateArrayResults($category->products, 10);

dd($paginated);
```

**Comment by jsdecena** [comment]
@authemany2k 

```
$category = $this->categoryRepo->findCategoryById($id);
$paginated = $this->categoryRepo->paginateArrayResults($category->products, 10);
```

`$category->products` will return a collection. You need to use `$category->products()->all()`

**Comment by authemany2k** [comment]
Am also facing the same problem please how can i limit products in category view On Apr 18, 2018 10:43, dimasip <notifications@github.com> wrote:i try to limit product per page in category page.
i can customize limit in search page.
return view('front.products.product-search', [
'products' => $this->productRepo->paginateArrayResults($products->all(), 10)
]);
how to limit product in category page?

**Comment by authemany2k** [comment]
True i notice this same issue please lets paginate the products in category view. If u have thousands of products they are all going to be displayed
