### ISSUE TITLE
Product page pagination not working

### ISSUE THREAD

**Issue by authemany2k** [Laracommerce/laracom#49]
Please I found out that the product page pagination is not working.
when I select a category the products in the category are not paginated even though I can see that the code is implement but is not doing the work.
Please can you just check and resolve the issue. 

Also the  front page products too should be limited to say 12 items per New Arrivals and Featured Products

**Comment by belguinan** [comment]
Hello,
it's working, 
If you look into "ProductController@search"
You gonna find this line :
$productsResult = $this->productRepo->paginateArrayResults($products, 10);

The front page is hardcoded, they select all products in the category_id 2 and 3
You should customize it as you like

search for you HomeController@index
App/Http/Controllers/Front/HomeController

**Comment by authemany2k** [comment]
Great i can see that the search result for products is paginated but the products in category page is not paginated. Anyway i will fix it myself it's not really an issue just want to point it out.

**Comment by klukiyan** [comment]
@authemany2k 
have you fix it? can you give a hint how you did it?

**Comment by authemany2k** [comment]
Ok fine but apart from search result pagination the products in category in general need to be paginated. Thanks i will work on it myself. On Apr 24, 2018 21:53, belguinan <notifications@github.com> wrote:Hello,
it's working,
If you look into "ProductController@search"
You gonna find this line :
$productsResult = $this->productRepo->paginateArrayResults($products, 10);
The front page is hardcoded, they select all products in the category_id 2 and 3
You should customize it as you like
search for you HomeController@index
App/Http/Controllers/Front/HomeController
