### ISSUE TITLE
listRoles() method in EmployeeRepository returns empty collection

### ISSUE THREAD

**Issue by enricoromeo** [Laracommerce/laracom#52]
I'm not sure that it's really an issue but a get an empty collection from method listRoles() In EmployeeRepository

for now I replaced listRoles() with:

  public function listRolesByEmployee(Employee $employee): Collection
    {
       return $employee->roles()->get();
    }

kindly Regards

**Comment by jsdecena** [comment]
Maybe you have not seeded the data?

**Comment by enricoromeo** [comment]
no, I've tested with data in db.

from employee controller first I get the Employee using findEmployeeById() then I get a list of roles passing the Employee obj to listRoles method modified like this: 

public function listRoles(Employee $employee): Collection
    {
        return $employee->roles()->get();
    }

in this way it works.

The method listRoles() should have worked even without parameter but it didn't, I don't understand why.

is not a relevant issue, maybe I'm wrong, you can close it if you want.

Thanks

**Comment by jsdecena** [comment]
You need to pass the employee model to the repository:

```
$employee = $this->employeeRepo->findEmployeeById($id);
$employeeRepo = new EmployeeRepository($employee);
$roles = $employeeRepo->listRoles();
dd($roles);

// But you can do direct access also if you want with
dd($employee->roles);
```
