### ISSUE TITLE
Delete cascade

### ISSUE THREAD

**Issue by belguinan** [Laracommerce/laracom#53]
Hello,
In databases it's great if you make the delete on cascade on all foreign keys,
for exemple if you make a new customer and a new address, once you destroy the customer; Addresses page doesnt work anymore, It throws an exception so you need to delete the address manually

**Comment by jsdecena** [comment]
In an enterprise level, we do not hard delete anything. Come to think when this customer has an order and you delete it, the history will be gone and you will have an orphaned order. The same way with the addresses, you need to keep backtrack all your history way from when you start your store. It can have a soft delete though.
