### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by risabhx** [Laracommerce/laracom#59]

**Comment by jsdecena** [comment]
You have to check the laravel.log to see which one it can't see.

**Comment by risabhx** [comment]
C:\\xampp\\htdocs\\laravelShop\\artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

**Comment by jsdecena** [comment]
You have to throw xampp out of the garbage can. It will not work on modern frameworks. :)

**Comment by risabhx** [comment]
so there is no way i can play on localhost ?

**Comment by jsdecena** [comment]
There is, read here: https://github.com/Laracommerce/laracom/wiki/Installation

**Comment by mirr** [comment]
You may want to try http://laradock.io/
