### ISSUE TITLE
Redo category by using nested set model

### ISSUE THREAD

**Issue by jsdecena** [Laracommerce/laracom#60]
Theory: https://en.wikipedia.org/wiki/Nested_set_model
Package: https://github.com/etrepat/baum

**Comment by jsdecena** [comment]
Both have a good number of stars but a few PRs that wasn't being merged until today. We'll see which one is effective when I use it. :) Thanks for the heads up!

**Comment by babatundeakinse** [comment]
Is this meant to cater for Categories & subcategories ?

**Comment by jsdecena** [comment]
Updated the categories with nested set with help from @belguinan 

See commit https://github.com/Laracommerce/laracom/commit/1a9707d8e5c0275f9946428970fd87e2bf5bfd58
