### ISSUE TITLE
feature request: product brand

### ISSUE THREAD

**Issue by lucassmacedo** [Laracommerce/laracom#62]
Hello! First this project is awesome! I want to contribute. 
My first suggestion is add product brand crud and associate with the product.

**Comment by jsdecena** [comment]
Hi @lucassmacedo - There is already existing in the dev branch: 

Here is the test : [Brand Feature Test](https://github.com/Laracommerce/laracom/blob/develop/tests/Feature/Admin/Brands/BrandFeatureTest.php)

You can now do a crud for brands and associate it with the product

**Comment by lucassmacedo** [comment]
Thanks @jsdecena I have not seen it, please close this issue xD
