### ISSUE TITLE
database seeder has got a Error

### ISSUE THREAD

**Issue by m-salahi** [Laracommerce/laracom#69]
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Sierra Leone' for key 'countries_name_unique' (SQL: insert into `countries` (`name`, `iso`
  , `iso3`, `numcode`, `phonecode`, `status`, `updated_at`, `created_at`) values (Sierra Leone, SWE, QAT, 8, 1, 1, 2018-06-23 12:11:13, 2018-06-23 12:11:13))`
Hi. Every time I run `php artisan migrate --seed` this error appeared. sometimes country name is changed and error appeared

**Comment by jsdecena** [comment]
@m-salahi - Is it the latest develop version? If not, pull the latest one. `git pull origin develop`

**Comment by m-salahi** [comment]
I downloaded here.
