### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jsdecena** [Laracommerce/laracom#72]
Create documentation under `/docs` for [Read the Docs](https://laracom.readthedocs.io/en/latest)

**Comment by AhSem** [comment]
Will you include a section on how to setup confirmation email sent to the buyer?

Currently, I saw MailChimp and Mail Server setups, but I am not sure how to use them. When people buy via Paypal, they only get PayPal payment notification. 

It would be nice to know how to setup custom email to include own logo, tracking number and more info.

**Comment by jsdecena** [comment]
@AhSem It will come but not a priority

**Comment by jbiddulph** [comment]
I just setup my laracom site but the styles are not linking?! what to do?

**Comment by jsdecena** [comment]
@jbiddulph Run `npm run dev` as per the [instruction](https://github.com/Laracommerce/laracom#build-and-compile-assets)

**Comment by phannaly** [comment]
Hi @jsdecena Do you have time look at this Laravel document package 
https://github.com/saleem-hadad/larecipe
If you like it and want to make this document, I would love to create PR for your docs.

**Comment by jsdecena** [comment]
@phannaly Wow. This is nice. Yup, we can build something like that and a PR is much appreciated! :)

**Comment by phannaly** [comment]
Yeah @jsdecena  but first you need prepare it. Did https://shop.laracom.net use this repo as the source project? If yeah, you just install above package and let me PR the markdown document for you. Everything will be inside `/docs`

**Comment by jsdecena** [comment]
Yup, it is using this repo. 

@phannaly Installed: https://github.com/Laracommerce/laracom/commit/af4ae0fb3325fa98cc1f36c12a14fe7e01fe0c94

**Comment by jsdecena** [comment]
@phannaly It is working now! https://shop.laracom.net/docs/1.4.6/overview 💯 

I think I can close this already :)

**Comment by phannaly** [comment]
Wow cool @jsdecena but you should update readme for link to this documents

**Comment by jsdecena** [comment]
@phannaly develop branch is updated

**Comment by phannaly** [comment]
Has ha my bad
