### ISSUE TITLE
Product price is not taking from the combination price

### ISSUE THREAD

**Issue by AhSem** [Laracommerce/laracom#78]
The product has a few combinations, each with different price. So I let the product price be 0.00 and set them separately in combination.

![image](https://user-images.githubusercontent.com/10499467/42790318-076d944a-899d-11e8-9af5-08c5f77bc7d2.png)

![image](https://user-images.githubusercontent.com/10499467/42790304-ea35747e-899c-11e8-99a6-dca298b80ab7.png)

As a result, the product price as seen by public is 0.00, as shown below.
![image](https://user-images.githubusercontent.com/10499467/42790352-2e44a004-899d-11e8-8f8e-428614955468.png)

Is this considered an issue/bug or it is settings/configuration issue?

**Comment by jsdecena** [comment]
I have implemented in my other project that you can set a default combination so we can show it in the front end. Will include that in the update.

**Comment by AhSem** [comment]
No, I don't see it in my version. 

![image](https://user-images.githubusercontent.com/10499467/42799566-ddaf3b44-89ca-11e8-8152-40ee8ec62375.png)

**Comment by AhSem** [comment]
Please reopen this issue. Thank you.

I forked from this commit and did a little bit of changes on my own.

![image](https://user-images.githubusercontent.com/10499467/42800427-69e741da-89ce-11e8-92c7-42f28d2bab7f.png)

Does this commit already include the "Default price" option as mentioned?

* by the way, I am quite new to git. How should I pull new commits from Laracom and merge with my own repo (which is forked from the Laracom)

**Comment by jsdecena** [comment]
please rebase to the current `develop` branch.

**Comment by AhSem** [comment]
Fixed at develop branch.
