### ISSUE TITLE
Product is displayed even if the status is 'Disabled'

### ISSUE THREAD

**Issue by AhSem** [Laracommerce/laracom#79]
I set a product status to 'Disabled, but it is still shown to public.

![image](https://user-images.githubusercontent.com/10499467/42790423-7af0bac8-899d-11e8-8e3e-9288987a707e.png)

You can refer to the production site [here](http://shop.smata.com.my/category/clothing).

Question: Does the 'Disable' status mean that the product should not be displayed to the public?

**Comment by jsdecena** [comment]
I see this. Will be updating the latest dev branch today including this.
