### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image' cannot be null (SQL: insert into `sliders` (`name`, `description`, `image`, `updated_at`, `created_at`) values (Apple Casing, Description, , 2018-07-20 03:08:05, 2018-07-20 03:08:05))

### ISSUE THREAD

**Issue by IsoftTech** [Laracommerce/laracom#80]
I was trying to customize my sliders through the admin by adding some code. But every time I add image,I got this error
The Error:
![capture png1](https://user-images.githubusercontent.com/34220799/42797540-f64d7660-898f-11e8-9ae2-bc00017344da.PNG)
My controller:
![realcontrollers](https://user-images.githubusercontent.com/34220799/42797571-1bb5aa1c-8990-11e8-97fc-c4b1c6a99a0f.PNG)
My Route:
![controllers](https://user-images.githubusercontent.com/34220799/42797590-3a1e21d2-8990-11e8-8085-02e07d06aa0f.PNG)
Again, i wanted the slider menu to show on the admin sidebar, but it's showing. looks like there's some role i need to add.
Slider Index:
![slidersindex](https://user-images.githubusercontent.com/34220799/42797708-af283242-8990-11e8-8987-70dc2e9b3ac0.PNG)
SliderCreate:
![sliderscreate](https://user-images.githubusercontent.com/34220799/42797715-bac6ee18-8990-11e8-95d2-3c1e4677ec6b.PNG)
SideBar:
![sidebar](https://user-images.githubusercontent.com/34220799/42797753-fa067abc-8990-11e8-9837-0078e5f27583.PNG)
Admin SideBar:
![adminsider](https://user-images.githubusercontent.com/34220799/42797764-0baae65e-8991-11e8-86ad-c2920469b49e.PNG)
Please sir, if there is any thing i did wrong you can help me by showing how the code should look like.
Regard, Abraham

**Comment by jsdecena** [comment]
You cannot be a programmer if you cannot see the details:

The errors said:
> Column 'image' cannot be null

Means, the column `image` in the database is defined as **NOT NULL** so you need to check why when you save your slider, it gets `null` meaning it doesn't get the value you are trying to set.

Here's your code, find the bug:

```
$slider = new Slider();
$slider->name = $request->name;
$slider->description = $request->description;
$slider->image = $request->iamgename;
$slider->save();
```

**Comment by iammikek** [comment]
@jsdecena @IsoftTech was the slider functionality ever part of 'core' laracom? I'm looking to add it so wandering if there is anything already to build on.
