### ISSUE TITLE
"vendor" directory does not exist (when I downloaded the application)

### ISSUE THREAD

**Issue by augPHP** [Laracommerce/laracom#84]
How can I get the laracom's "vendor" directory?

I tried to copy from another app and I got this error mesage (when I ran "php artisan migrate":

"PHP Warning: require (C:\xampp\htdocs\laracom_master\vendor\composer/../../app/Helpers/DateFormat.php): failed to open stream: No such file or directory in C:\xampp\htdocs\laracom_master\vendor\composer\autoload_real.php on line 66"

**Comment by jsdecena** [comment]
@augPHP You have to install [composer](http://getcomposer.org/) run `composer install`. Also, it is not advisable to use xampp for this app. throw it in your rubbish bin.
