### ISSUE TITLE
Deleting Product not working

### ISSUE THREAD

**Issue by juddfranklin1** [Laracommerce/laracom#85]
https://shop.laracom.net/admin/products deleting a product does not actually delete a product, although the success message is displayed.

I have reproduced this on my local install of laracom and a development server version of laracom.

**Comment by jsdecena** [comment]
Sorry about this. I have fixed it on the latest `develop` branch [commit](https://github.com/Laracommerce/laracom/commit/7cf7edae46f8bb915a867f8b9ad76949edb2c1f3)

**Comment by juddfranklin1** [comment]
Thanks! I will confirm

**Comment by juddfranklin1** [comment]
I can confirm that on my local installation updating the ProductController fixes the delete behavior.

**Comment by jsdecena** [comment]
Merged to master as this is a critical issue :)
