### ISSUE TITLE
php artisan migrate --seed error

### ISSUE THREAD

**Issue by patrickpeng830** [Laracommerce/laracom#86]
Hello, how to fix it ?

php artisan migrate --seed
Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `employees` add unique `employees_email_u
  nique`(`email`))

In PDOStatement.php line 143:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

In PDOStatement.php line 141:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by Datalink-Wouter** [comment]
Inside app/Providers/AppServiceProvider.php :
Add  "use Illuminate\Support\Facades\Schema;" to the top.

Next change the boot() method to this:

`public function boot()
{
    Cashier::useCurrency(config('cart.currency'), config('cart.currency_symbol'));
    Schema::defaultStringLength(191);
}`

**Comment by jsdecena** [comment]
@patrickpeng830 By default installation, we do not encounter this. But you can bypass that using the [defaultStringLength()](https://laravel.com/docs/5.6/migrations#indexes) method

![Imgur](https://i.imgur.com/1yrKAVN.png)
