### ISSUE TITLE
Change password: not hashed

### ISSUE THREAD

**Issue by Datalink-Wouter** [Laracommerce/laracom#87]
Hi,

I noticed when an employee changes the password (top right => Profile) the password is stored without hashing.
When you change password through "List employees" in the left menu it works fine.

When the password is not changed, you get an error because the password cannot be empty.

Controller: Http/Controllers/Admin/EmployeeController.php
Method: updateEmployee()

Regards

**Comment by jsdecena** [comment]
@Datalink-Wouter - Fixed on this commit https://github.com/Laracommerce/laracom/commit/9da7cffd87761e3d0098fc6591f46d7b7836c122
