### ISSUE TITLE
_update_the_category()

### ISSUE THREAD

**Issue by sajeevcrayons** [Laracommerce/laracom#89]
public function it_can_update_the_category()
    {
        $cover = UploadedFile::fake()->image('file.png', 600, 600);
        $parent = factory(Category::class)->create();

        $params = [
            'name' => 'Boys',
            'slug' => 'boys',
            'description' => $this->faker->paragraph,
            'status' => 1,
            'parent' => $parent->id,
            'cover' => $cover
        ];

        $category = new CategoryRepository($this->category);
        $updated = $category->updateCategory($params);

        $this->assertInstanceOf(Category::class, $updated);
        $this->assertEquals($params['name'], $updated->name);
        $this->assertEquals($params['slug'], $updated->slug);
        $this->assertEquals($params['description'], $updated->description);
        $this->assertEquals($params['status'], $updated->status);
        $this->assertEquals($params['parent'], $updated->parent_id);
        $this->assertEquals($params['cover'], $cover);
    }

hello i want to know this line $category = new CategoryRepository($this->category); 
in this $this->category i dont understand what is passing this categoryrepository plz tell detaily

**Comment by sajeevcrayons** [comment]
i didnt get plz tell detailyy

**Comment by jsdecena** [comment]
Cannot help you more. Sorry.
