### ISSUE TITLE
Brands and their related products

### ISSUE THREAD

**Issue by chrisformula** [Laracommerce/laracom#94]
How can I return the products relating to a specific brand? ie: Page with brand names and when clicked will return the products?

**Comment by jsdecena** [comment]
@chrisformula There is method in brand repository called [listProducts()](https://github.com/Laracommerce/laracom/blob/develop/app/Shop/Brands/Repositories/BrandRepository.php#L98) that you can use.

You can do this via:
```
$brandRepo = new BrandRepository($brand);
$products = $brandRepo->listProducts();
dd($products);
```

**Comment by chrisformula** [comment]
Doesn't work mate keep getting Too few arguments to function App\Http\Controllers\Front\ProductController::brandProducts(), 0 passed and exactly 1 expected

It's ok don't worry about it I am going to rewrite in a stack that I know. Laravel isn't for me

**Comment by jsdecena** [comment]
what brandProducts()?
