### ISSUE TITLE
SQL error on Checkout

### ISSUE THREAD

**Issue by chrisformula** [Laracommerce/laracom#95]
Whenever I check out an amount above 1000 I get this error, why?
QLSTATE[HY000]: General error: 1366 Incorrect decimal value: '1,009.00' for column 'total' at row 1 (SQL: insert into `orders`

**Comment by jsdecena** [comment]
@chrisformula This is actually a bug. Will commit a PR on develop branch in a while.

**Comment by chrisformula** [comment]
Thank you so much

**Comment by jsdecena** [comment]
@chrisformula Can you pull the latest develop ([fix](https://github.com/Laracommerce/laracom/commit/840635ba9b6cd972544707756e5d84c1f19d7c9f)) and see if it fixes it? Thanks!
