### ISSUE TITLE
New in laravel (style issue)

### ISSUE THREAD

**Issue by nightw0lv** [Laracommerce/laracom#97]
i have installed in xampp this application and i have a problem displaying any style in admin panel or front page
in source of page the link of css is http://localhost:8000/css/admin.min.css
but when i click on it i get an error Ooops, we cannot find what you are looking for. Please try again.
http://prntscr.com/ks02xv

**Comment by thearyanahmed** [comment]
It is not mandatory to have xampp. And I think you did not place or miss-spelled your admin.min.css . Open the console and see there should be an 404 Resource not found error.Try and figure the actual path of your css file.
Should work

**Comment by thearyanahmed** [comment]
@nightw0lv  you just need to compile your assets with node
simply run 'npm install' in the root directory of your app.it will install all the dependencies (such as axios,vue etc) create .node_modules folder. then run 'npm run dev' in the same directory,it will compile your assets. npm is node package manager,similar to composer for php
